# Generated by Django 5.1.3 on 2024-11-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_customuser_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerproduct',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offerproduct',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
