# Generated by Django 5.1.3 on 2024-11-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_offerproduct_description_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='payment_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='number',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
