# Generated by Django 5.1.3 on 2024-11-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_offer_note_offer_payment_terms_alter_offer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
